
templates:
  #===========================================================================
  A4 landscape: !template
  #===========================================================================
    reportTemplate: simpleReport.jrxml
    tableData: jrDataSource
    attributes:
      map: !map
        maxDpi: 400
        width: 780
        height: 330
      paging: !paging
        default:
          scale: 1000
          overlap: 0
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMapPages {}
    - !createMap {}
    - !createDataSource
      inputMapper: {maps: datasource}
      processors:
        - !createMap {}
    
