throwErrorOnExtraParameters: true

templates:
  report: !template
    reportTemplate: report_A4.jrxml
    #tableData: topicpage1
    attributes:
      # Variables for header
      ch_logo: !string {}
      canton_logo: !string {}
      municipalitylogopath: !string {}
      crdppf_logo: !string {}
      
      # Variables for footer
      # Variables for title page
      municipality: !string {}
      report_title: !string {}
      propertylabel: !string {}
      extractsubtitlelabel: !string {}

      # Variables for TOC
      # Variables for topic page
      legendlabel: !string {}
      completlegendlabel: !string {} 
      legalbaseslabel: !string {} 
      legalprovisionslabel: !string {} 
      referenceslabel: !string {} 
      competentauthoritylabel: !string {} 

      #topicpage: !datasource
      datasource: !datasource
        attributes:
          topic_title: !string {}
          topic_text: !string {}
          map: !map
            width: 493
            height: 280
            maxDpi : 400
            dpiSuggestions: [150]

      map: !map
        width: 493
        height: 280
        maxDpi : 400
        dpiSuggestions: [150]

    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap {}
    - !createDataSource
       processors:
         - !createMap {}
    tableData: jrDataSource
