throwErrorOnExtraParameters: true

templates:
  report: !template
    outputFilename: ${yyyyMMddhhmmss}_extract
    reportTemplate: pdfextract.jrxml

    attributes:
      # Global variables
      extractid: !string {}
      pdfExtractIdLabel: !string {}
      placeholderlabel: !string {}
      pagelabel: !string {}
      appendiceslistlabel: !string {}

      # Variables for header
      ch_logo: !string {}
      canton_logo: !string {}
      municipalitylogopath: !string {}
      crdppf_logo: !string {}
      competentauthority: !string {}

      # Variables for footer

      # Variables for title page
      municipality: !string {}
      municipalitylabel: !string {}
      federalmunicipalitynumber: !string {}
      cadastre: !string {}
      cadastrelabel: !string {}
      extractsubtitlelabel: !string {}
      propertylabel: !string {}
      propertynumber: !string {}
      propertytype: !string {}
      propertyarealabel: !string {}
      propertyarea: !string {}
      EGRIDlabel: !string {}
      EGRIDnumber: !string {}
      creationdatelabel: !string {}
      extractcreationdate: !string {}
      extractoperatorlabel: !string {}
      certificationlabel: !string {}
      titlepage: !datasource
        attributes:
          title: !string {}
          certificationtext: !string {}
          certificationinstance: !string {}

      # Parameters for table of content
      toclabel: !string {}
      concernedtopics: !datasource
        attributes:
          topicname: !string {}
          documentlist: !table {}
      notconcernedtopics: !string {}
      emptytopics: !string {}

      # Variables for Glossar
      glossar: !datasource
        attributes:
          glossarlabel: !string {}
          definitions: !table {}
      
      # Variables for topic page
      legendlabel: !string {}
      bboxlegendlabel: !string {}
      completlegendlabel: !string {}
      legalbaseslabel: !string {}
      legalprovisionslabel: !string {}
      referenceslabel: !string {}
      competentauthoritylabel: !string {}

      basemapNorthArrow: !northArrow
        size: 17
        default:
          graphic: "file:///north.svg"
      scalebar: !scalebar
        width: 93
        height: 15
        default:
          fontSize: 7
      map: !map
        maxDpi: 400
        width: 493
        height: 280
        
      datasource: !datasource
        attributes:
          topicname: !string {}
          completelegend: !string {}
          bboxlegend: !datasource
            attributes:
              codegenre: !string {}
              teneur: !string {}
            default:
              - codegenre: ""
              - teneur: ""
          restrictions: !datasource
            attributes:
              codegenre: !string {}
              teneur: !string {}
              area: !string {}
              area_pct: !float {}
          legalbases: !datasource
            attributes:
              officialtitle: !string {}
              remoteurl: !string {}
          legalprovisions: !datasource
            attributes:
              officialtitle: !string {}
              remoteurl: !string {}
          references: !datasource
            attributes:
              officialtitle: !string {}
              remoteurl: !string {}
          authority: !datasource
            attributes:
              authorityname: !string {}
              authorityurl: !string {}
          northArrow: !northArrow
            size: 17
            default:
              graphic: "file:///north.svg"
          scalebar: !scalebar
            width: 93
            height: 15
            default:
              fontSize: 7
          map: !map
            maxDpi: 400
            width: 493
            height: 280

    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createNorthArrow
      inputMapper: {basemapNorthArrow: northArrow}
      outputMapper: {northArrowSubReport: northArrowSubReport}
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: basemap}
    - !createScalebar {}
    - !createDataSource
      processors:
      - !reportBuilder # compile all reports in current directory
        directory: '.'
      inputMapper: {glossar: datasource}
      outputMapper: {jrDataSource: glossar}
      processors:
      - !prepareTable
        inputMapper: {definitions: table}
        outputMapper: {table: definitions}
    - !createDataSource
      processors:
      - !reportBuilder # compile all reports in current directory
        directory: '.'
      inputMapper: {titlepage: datasource}
      outputMapper: {jrDataSource: titlepage}
    - !createDataSource
      processors:
      - !reportBuilder # compile all reports in current directory
        directory: '.'
      inputMapper: {concernedtopics: datasource}
      outputMapper: {jrDataSource: concernedtopics}
      processors:
      - !prepareTable
        inputMapper: {documentlist: table}
        outputMapper: {table: documentlist}
    - !createDataSource
      processors:
      - !reportBuilder # compile all reports in current directory
        directory: '.'
      inputMapper: {datasource: datasource}
      outputMapper: {jrDataSource: jrDataSource}
      processors:
      - !createNorthArrow {}
      - !createMap
        inputMapper: {map: map}
        outputMapper: {mapSubReport: mapSubReport}
      - !createScalebar {}
      - !createDataSource
        processors:
        - !reportBuilder # compile all reports in current directory
          directory: '.'
        inputMapper: {bboxlegend: datasource}
        outputMapper: {jrDataSource: bboxlegend}
      - !createDataSource
        processors:
        - !reportBuilder # compile all reports in current directory
          directory: '.'
        inputMapper: {restrictions: datasource}
        outputMapper: {jrDataSource: restrictions}
      - !createDataSource
        processors:
        - !reportBuilder # compile all reports in current directory
          directory: '.'
        inputMapper: {legalbases: datasource}
        outputMapper: {jrDataSource: legalbases}
      - !createDataSource
        processors:
        - !reportBuilder # compile all reports in current directory
          directory: '.'
        inputMapper: {legalprovisions: datasource}
        outputMapper: {jrDataSource: legalprovisions}
      - !createDataSource
        processors:
        - !reportBuilder # compile all reports in current directory
          directory: '.'
        inputMapper: {references: datasource}
        outputMapper: {jrDataSource: references}
      - !createDataSource
        processors:
        - !reportBuilder # compile all reports in current directory
          directory: '.'
        inputMapper: {authority: datasource}
        outputMapper: {jrDataSource: authority}
