throwErrorOnExtraParameters: false

templates:
  report: !template
    outputFilename: ${yyyyMMddhhmmss}_extract
    reportTemplate: pdfextract.jrxml

    attributes:
      # Global variables
      reporttype: !string {}
      extractid: !string {}
      pdfExtractIdLabel: !string {}
      placeholderlabel: !string {}
      pagelabel: !string {}
      appendiceslistlabel: !string {}

      # Variables for header
      ch_logo: !string {}
      canton_logo: !string {}
      municipalitylogopath: !string {}
      crdppf_logo: !string {}
      competentauthority: !string {}

      # Variables for footer

      # Variables for title page
      municipality: !string {}
      municipalitylabel: !string {}
      federalmunicipalitynumber: !string {}
      cadastre: !string {}
      cadastrelabel: !string {}
      extractsubtitlelabel: !string {}
      propertylabel: !string {}
      propertynumber: !string {}
      propertytype: !string {}
      propertyarealabel: !string {}
      propertyarea: !string {}
      EGRIDlabel: !string {}
      EGRIDnumber: !string {}
      creationdatelabel: !string {}
      extractcreationdate: !string {}
      extractoperatorlabel: !string {}
      responsibleauthoritylabel: !string {}
      responsibleauthorityTxt: !string {}
      certificationlabel: !string {}
      titlepage: !datasource
        attributes:
          title: !string {}
          certificationtext: !string {}
          certificationinstance: !string {}

      # Parameters for table of content
      toclabel: !string {}
      pdfConcernedTopicsLabel1: !string {}
      pdfConcernedTopicsLabel2: !string {}
      #~ pdfConcernedTopicsLabel3:  !string {}
      pdfNotConcernedTopicsLabel: !string {}
      pdfEmptyTopicsLabel: !string {}
      pdfGeneralInformationLabel: !string {}
      pdfGeneralInformationTxt: !string {}
      pdfFurtherInformationLabel: !string {}
      pdfFurtherInformationTxt: !string {}
      pdfBaseDataLabel: !string {}
      pdfBaseDataTxt: !string {}
      concernedtopics: !datasource
        attributes:
          topicname: !string {}
          documentlist: !table {}
      notconcernedtopics: !string {}
      emptytopics: !string {}

      # Variables for Glossar
      glossar: !datasource
        attributes:
          glossarlabel: !string {}
          definitions: !table {}

      # Variables for topic page
      legendlabel: !string {}
      bboxlegendlabel: !string {}
      completlegendlabel: !string {}
      legalbaseslabel: !string {}
      legalprovisionslabel: !string {}
      referenceslabel: !string {}
      competentauthoritylabel: !string {}

      basemapNorthArrow: !northArrow
        size: 19
        default:
          graphic: "file:///north.svg"
      scalebar: !scalebar
        width: 93
        height: 15
        default:
          fontSize: 6
          align: "center"
          padding: 2
          backgroundColor: "rgba(255, 255, 255, 255)"
      map: !map
        maxDpi: 400
        width: 493
        height: 280

      datasource: !datasource
        attributes:
          topicname: !string {}
          completelegend: !string {}
          bboxlegend: !datasource
            attributes:
              codegenre: !string {}
              teneur: !string {}
            default:
              - codegenre: ""
              - teneur: ""
          restrictions: !datasource
            attributes:
              codegenre: !string {}
              teneur: !string {}
              area: !string {}
              area_pct: !float {}
          legalbases: !datasource
            attributes:
              officialtitle: !string {}
              officialnb: !string {}
              remoteurl: !string {}
          legalprovisions: !datasource
            attributes:
              officialtitle: !string {}
              officialnb: !string {}
              remoteurl: !string {}
          references: !datasource
            attributes:
              officialtitle: !string {}
              officialnb: !string {}
              remoteurl: !string {}
          authority: !datasource
            attributes:
              authorityname: !string {}
              authorityurl: !string {}
          northArrow: !northArrow
            size: 19
            default:
              graphic: "file:///north.svg"
          scalebar: !scalebar
            width: 93
            height: 15
            default:
              fontSize: 6
              align: "center"
              padding: 2
              backgroundColor: "rgba(255, 255, 255, 255)"
          map: !map
            maxDpi: 400
            width: 493
            height: 280

    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !configureHttpRequests  &configureHttpRequests
        httpProcessors:
        - !forwardHeaders
            matchers:
            - !localMatch {}
            - !dnsMatch {}
            headers:
            - Cookie
            - Host
        - !forwardHeaders
            headers:
            - Referer
        - !restrictUris
            matchers:
            - !localMatch
              pathRegex: /dev_crdppf2/*
            - !dnsMatch
              host: localhost
              port: 6566
            - !dnsMatch
              host: localhost
              port: 80
            - !dnsMatch
              host: sitn.ne.ch
              port: 443
            - !acceptAll {}
    - !createNorthArrow
      inputMapper: {basemapNorthArrow: northArrow}
      outputMapper: {northArrowSubReport: northArrowSubReport}
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: basemap}
    - !createScalebar {}
    - !createDataSource
      processors:
      - !reportBuilder # compile all reports in current directory
        directory: '.'
      inputMapper: {glossar: datasource}
      outputMapper: {jrDataSource: GlossaryDataSource}
      processors:
      - !prepareTable
        inputMapper: {definitions: table}
        outputMapper: {tableDataSource: DefinitionsTableSource}
    - !createDataSource
      processors:
      - !reportBuilder # compile all reports in current directory
        directory: '.'
      inputMapper: {titlepage: datasource}
      outputMapper: {jrDataSource: TitlepageDataSource}
    - !createDataSource
      processors:
      - !reportBuilder # compile all reports in current directory
        directory: '.'
      inputMapper: {concernedtopics: datasource}
      outputMapper: {jrDataSource: ConcernedTopicsDataSource}
      processors:
      - !prepareTable
        inputMapper: {documentlist: table}
        outputMapper: {tableDataSource: DocumentlistTableSource}
    - !createDataSource
      processors:
      - !reportBuilder # compile all reports in current directory
        directory: '.'
      inputMapper: {datasource: datasource}
      outputMapper: {jrDataSource: MainDataSource}
      processors:
      - !createNorthArrow {}
      - !createMap
        inputMapper: {map: map}
        outputMapper: {mapSubReport: mapSubReport}
      - !createScalebar {}
      - !createDataSource
        processors:
        - !reportBuilder # compile all reports in current directory
          directory: '.'
        inputMapper: {bboxlegend: datasource}
        outputMapper: {jrDataSource: BBOXLegendDataSource}
      - !createDataSource
        processors:
        - !reportBuilder # compile all reports in current directory
          directory: '.'
        inputMapper: {restrictions: datasource}
        outputMapper: {jrDataSource: RestrictionsDataSource}
      - !createDataSource
        processors:
        - !reportBuilder # compile all reports in current directory
          directory: '.'
        inputMapper: {legalbases: datasource}
        outputMapper: {jrDataSource: LegalbasesDataSource}
      - !createDataSource
        processors:
        - !reportBuilder # compile all reports in current directory
          directory: '.'
        inputMapper: {legalprovisions: datasource}
        outputMapper: {jrDataSource: LegalProvisionsDataSource}
      - !createDataSource
        processors:
        - !reportBuilder # compile all reports in current directory
          directory: '.'
        inputMapper: {references: datasource}
        outputMapper: {jrDataSource: ReferencesDataSource}
      - !createDataSource
        processors:
        - !reportBuilder # compile all reports in current directory
          directory: '.'
        inputMapper: {authority: datasource}
        outputMapper: {jrDataSource: AuthorityDataSource}
