throwErrorOnExtraParameters: true

templates:
  report: !template
    outputFilename: ${yyyyMMddhhmmss}_extract
    reportTemplate: mainpage.jrxml

    attributes:
      # Global variables
      extractid: !string {}
      placeholderlabel: !string {}
      pagelabel: !string {}
      appendiceslistlabel: !string {}
      
      # Variables for header
      ch_logo: !string {}
      canton_logo: !string {}
      municipalitylogopath: !string {}
      crdppf_logo: !string {}
      competentauthority: !string {} 
      
      # Variables for footer
      # Variables for title page
      municipality: !string {}
      municipalitylabel: !string {}
      federalmunicipalitynumber: !string {}
      cadastre: !string {}
      cadastrelabel: !string {}
      title: !string {}
      extractsubtitlelabel: !string {}
      propertylabel: !string {}
      propertynumber: !string {}
      propertytype: !string {}
      propertyarealabel: !string {}
      propertyarea: !string {}
      EGRIDlabel: !string {}
      EGRIDnumber: !string {}
      creationdatelabel: !string {}
      extractcreationdate: !string {}
      extractoperatorlabel: !string {}
      certificationlabel: !string {}
      certificationtext: !string {}

      # Variables for Glossar
      glossar: !datasource
        attributes:
          glossarlabel: !string {}
          definitions: !table {}
      
      # Variables for topic page
      legendlabel: !string {}
      maplegendlabel: !string {}
      completlegendlabel: !string {} 
      legalbaseslabel: !string {} 
      legalprovisionslabel: !string {} 
      referenceslabel: !string {} 
      competentauthoritylabel: !string {} 

      basemapNorthArrow: !northArrow
        size: 17
        default:
          graphic: "file:///north.svg"
      scalebar: !scalebar
        width: 93
        height: 15
        default:
          fontSize: 7
      map: !map
        maxDpi: 400
        width: 493
        height: 280
        
      toc: !datasource
        attributes:
          toctitle: !string {}
          concernedtopics: !string {}
          notconcernedtopics: !string {}         
          emptytopics: !string {}         
      datasource: !datasource
        attributes:
          topicname: !string {}
          completelegend: !string {}
          propertyarea: !string {}
          restrictions: !datasource
            attributes:
              codegenre: !string {}
              teneur: !string {}
              area: !string {}
          legalbases: !datasource
            attributes:
              officialtitle: !string {}
              remoteurl: !string {}
          legalprovisions: !datasource
            attributes:
              officialtitle: !string {}
              remoteurl: !string {}
          references: !datasource
            attributes:
              officialtitle: !string {}
              remoteurl: !string {}
          authority: !datasource
            attributes:
              authorityname: !string {}
              authorityurl: !string {}
          northArrow: !northArrow
            size: 17
            default:
              graphic: "file:///north.svg"
          scalebar: !scalebar
            width: 93
            height: 15
            default:
              fontSize: 7
          map: !map
            maxDpi: 400
            width: 493
            height: 280

    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createNorthArrow
      inputMapper: {basemapNorthArrow: northArrow}
      outputMapper: {northArrowSubReport: northArrowSubReport}
    - !createScalebar {}
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: basemap}
    - !createDataSource
      processors:
      - !reportBuilder # compile all reports in current directory
        directory: '.'
      inputMapper: {glossar: datasource}
      outputMapper: {jrDataSource: glossar}
      processors:
      - !prepareTable
        inputMapper: {definitions: table}
        outputMapper: {table: definitions}
    - !createDataSource
      processors:
      - !reportBuilder # compile all reports in current directory
        directory: '.'
      inputMapper: {toc: datasource}
      outputMapper: {jrDataSource: toc}
    - !createDataSource
      processors:
      - !reportBuilder # compile all reports in current directory
        directory: '.'
      inputMapper: {datasource: datasource}
      outputMapper: {jrDataSource: jrDataSource}
      processors:
      - !createNorthArrow {}
      - !createScalebar {}
      - !createMap
        inputMapper: {map: map}
        outputMapper: {mapSubReport: mapSubReport}
      - !createDataSource
        processors:
        - !reportBuilder # compile all reports in current directory
          directory: '.'
        inputMapper: {restrictions: datasource}
        outputMapper: {jrDataSource: restrictions}
      - !createDataSource
        processors:
        - !reportBuilder # compile all reports in current directory
          directory: '.'
        inputMapper: {legalbases: datasource}
        outputMapper: {jrDataSource: legalbases}
      - !createDataSource
        processors:
        - !reportBuilder # compile all reports in current directory
          directory: '.'
        inputMapper: {legalprovisions: datasource}
        outputMapper: {jrDataSource: legalprovisions}
      - !createDataSource
        processors:
        - !reportBuilder # compile all reports in current directory
          directory: '.'
        inputMapper: {references: datasource}
        outputMapper: {jrDataSource: references}
      - !createDataSource
        processors:
        - !reportBuilder # compile all reports in current directory
          directory: '.'
        inputMapper: {authority: datasource}
        outputMapper: {jrDataSource: authority}
