throwErrorOnExtraParameters: true

templates:
  report: !template
    outputFilename: ${yyyyMMddhhmmss}_extract
    reportTemplate: dynamictables.jrxml

    attributes:
      # Global variables
      placeholderlabel: !string {}
      
      # Variables for header
      ch_logo: !string {}
      canton_logo: !string {}
      municipalitylogopath: !string {}
      crdppf_logo: !string {}
      competentauthority: !string {} 
      
      # Variables for footer
      # Variables for title page
      municipality: !string {}
      municipalitylabel: !string {}
      federalmunicipalitynumber: !string {}
      cadastre: !string {}
      title: !string {}
      extractsubtitlelabel: !string {}
      propertylabel: !string {}
      propertynumber: !string {}
      propertytype: !string {}
      propertyarealabel: !string {}
      propertyarea: !string {}
      EGRIDlabel: !string {}
      EGRIDnumber: !string {}
      creationdatelabel: !string {}
      extractcreationdate: !string {}
      extractoperatorlabel: !string {}
      certificationlabel: !string {}
      certificationtext: !string {}

      # Variables for TOC
      # Variables for topic page
      legendlabel: !string {}
      completlegendlabel: !string {} 
      legalbaseslabel: !string {} 
      legalprovisionslabel: !string {} 
      referenceslabel: !string {} 
      competentauthoritylabel: !string {} 

      scalebar: !scalebar
        width: 150
        height: 20
        default:
          fontSize: 8
      basemap: !map
        maxDpi: 400
        width: 493
        height: 280
        
      datasource: !datasource
        attributes:
          topicname: !string {}
          northArrow: !northArrow
            size: 40
            default:
              graphic: "file:///north.svg"
          scalebar: !scalebar
            width: 150
            height: 20
            default:
              fontSize: 8
          map: !map
            maxDpi: 254
            width: 493
            height: 280
          topicdata: !datasource
            attributes:
              item: !string {}
              table: !table {}
          
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createScalebar {}
    - !createMap
      inputMapper: {basemap: map}
      outputMapper: {mapSubReport: basemap}
    - !createDataSource
      processors:
      - !createNorthArrow {}
      - !createScalebar {}
      - !createMap {}
      - !createDataSource
        processors:
        - !prepareTable {}
          #~ dynamic: true
        - !reportBuilder # compile all reports in current directory
          directory: '.'
        inputMapper: {topicdata: datasource}
        outputMapper: {jrDataSource: topicdata}