throwErrorOnExtraParameters: true

templates:
    A4 portrait: !template
        reportTemplate: multimap.jrxml
        tableData: jrDataSource
        attributes:
            title: !string {}
            comments: !string {}
            datasource: !datasource
                attributes:
                    topicname: !string {}
                    description: !string {}
                    map: !map
                        maxDpi: 254
                        width: 200
                        height: 200

        processors:
        - !reportBuilder # compile all reports in current directory
            directory: '.'
        - !createDataSource
            processors:
            - !createMap {}